# Generated by Django 4.2.3 on 2023-08-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('height', models.IntegerField(verbose_name='Высота букета')),
                ('width', models.IntegerField(verbose_name='Ширина букета')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_site.bouquet')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_site.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_site.componenttype'),
        ),
    ]
