# Generated by Django 4.2.3 on 2023-08-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterModelOptions(
            name='componentobject',
            options={'verbose_name': 'Компонент в заказе', 'verbose_name_plural': 'Компоненты в заказе'},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'verbose_name': 'Тип компонентов', 'verbose_name_plural': 'Типы компонентов'},
        ),
        migrations.RenameField(
            model_name='bouquet',
            old_name='name',
            new_name='title',
        ),
    ]
