# Generated by Django 4.2.3 on 2023-08-23 20:51

import datetime
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_site', '0003_consultationsignup_component_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория букетов',
                'verbose_name_plural': 'Категории букетов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_interval', django.contrib.postgres.fields.ranges.DateTimeRangeField(choices=[((datetime.datetime(2023, 8, 23, 20, 51, 54, 677914, tzinfo=datetime.timezone.utc), datetime.timedelta(seconds=7200)), 'Как можно скорее'), ((datetime.datetime(2023, 8, 24, 10, 51, 54, 677880, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 12, 51, 54, 677880, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 10 до 12'), ((datetime.datetime(2023, 8, 24, 12, 51, 54, 677880, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 14, 51, 54, 677880, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 12 до 14'), ((datetime.datetime(2023, 8, 24, 14, 51, 54, 677880, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 16, 51, 54, 677880, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 14 до 16'), ((datetime.datetime(2023, 8, 24, 16, 51, 54, 677880, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 18, 51, 54, 677880, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 16 до 18'), ((datetime.datetime(2023, 8, 24, 18, 51, 54, 677880, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 20, 51, 54, 677880, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 18 до 20')], verbose_name='Интервал доставки')),
                ('status', models.IntegerField(choices=[(0, 'Необработанный'), (1, 'В сборке'), (2, 'В доставке'), (3, 'Завершён')], db_index=True, default=0, verbose_name='Статус заказа')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='flower_site.componenttype', verbose_name='Тип компонента'),
        ),
        migrations.AlterField(
            model_name='componentobject',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_objects', to='flower_site.bouquet', verbose_name='Для букета'),
        ),
        migrations.AlterField(
            model_name='componentobject',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object', to='flower_site.component', verbose_name='Компонент'),
        ),
        migrations.CreateModel(
            name='OrderedBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 0)], verbose_name='Стоимость букета')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered', to='flower_site.bouquet', verbose_name='Букет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquets', to='flower_site.order')),
            ],
            options={
                'verbose_name': 'Букет в заказе',
                'verbose_name_plural': 'Букеты в заказах',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='categories',
            field=models.ManyToManyField(related_name='bouquets', to='flower_site.bouquetcategory', verbose_name='Категории букета (теги)'),
        ),
    ]
