# Generated by Django 4.2.3 on 2023-08-23 20:53

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_site', '0004_bouquetcategory_order_bouquet_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='bouquets', to='flower_site.bouquetcategory', verbose_name='Категории букета (теги)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_interval',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(choices=[((datetime.datetime(2023, 8, 23, 20, 53, 22, 831933, tzinfo=datetime.timezone.utc), datetime.timedelta(seconds=7200)), 'Как можно скорее'), ((datetime.datetime(2023, 8, 24, 10, 53, 22, 831899, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 12, 53, 22, 831899, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 10 до 12'), ((datetime.datetime(2023, 8, 24, 12, 53, 22, 831899, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 14, 53, 22, 831899, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 12 до 14'), ((datetime.datetime(2023, 8, 24, 14, 53, 22, 831899, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 16, 53, 22, 831899, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 14 до 16'), ((datetime.datetime(2023, 8, 24, 16, 53, 22, 831899, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 18, 53, 22, 831899, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 16 до 18'), ((datetime.datetime(2023, 8, 24, 18, 53, 22, 831899, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 8, 24, 20, 53, 22, 831899, tzinfo=datetime.timezone.utc)), 'Завтра (24.08) с 18 до 20')], verbose_name='Интервал доставки'),
        ),
    ]
