# Generated by Django 4.2.3 on 2023-08-23 20:59

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_site', '0005_alter_bouquet_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_interval',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Интервал доставки'),
        ),
    ]
