# Generated by Django 4.2.3 on 2023-08-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_site', '0006_alter_order_delivery_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_interval',
        ),
    ]
